# Generated by Django 5.2 on 2025-04-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodouble', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='client_id',
            field=models.CharField(max_length=255),
        ),
    ]
