# Generated by Django 5.2 on 2025-04-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodouble', '0002_alter_event_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='data',
        ),
    ]
