# Generated by Django 5.2 on 2025-04-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodouble', '0003_remove_event_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
    ]
