# Generated by Django 5.2 on 2025-04-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodouble', '0004_remove_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='product_id',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
